// This file was auto-generated by ML.NET Model Builder. 

using System;
using Classificador_de_vinhosML.Model;

namespace Classificador_de_vinhosML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Fixed_acidity = 7.4F,
                Volatile_acidity = 0.7F,
                Citric_acid = 0F,
                Residual_sugar = 1.9F,
                Chlorides = 0.076F,
                Free_sulfur_dioxide = 11F,
                Total_sulfur_dioxide = 34F,
                Density = 0.9978F,
                PH = 3.51F,
                Sulphates = 0.56F,
                Alcohol = @"9.4",
                Quality = 5F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Type with predicted Type from sample data...\n\n");
            Console.WriteLine($"Fixed_acidity: {sampleData.Fixed_acidity}");
            Console.WriteLine($"Volatile_acidity: {sampleData.Volatile_acidity}");
            Console.WriteLine($"Citric_acid: {sampleData.Citric_acid}");
            Console.WriteLine($"Residual_sugar: {sampleData.Residual_sugar}");
            Console.WriteLine($"Chlorides: {sampleData.Chlorides}");
            Console.WriteLine($"Free_sulfur_dioxide: {sampleData.Free_sulfur_dioxide}");
            Console.WriteLine($"Total_sulfur_dioxide: {sampleData.Total_sulfur_dioxide}");
            Console.WriteLine($"Density: {sampleData.Density}");
            Console.WriteLine($"PH: {sampleData.PH}");
            Console.WriteLine($"Sulphates: {sampleData.Sulphates}");
            Console.WriteLine($"Alcohol: {sampleData.Alcohol}");
            Console.WriteLine($"Quality: {sampleData.Quality}");
            Console.WriteLine($"\n\nPredicted Type value {predictionResult.Prediction} \nPredicted Type scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
